name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          echo "${{ secrets.DOCKER_TOKEN }}" docker login -u "sjalal0228" --password-stdin
          docker image build -t integrationninjas/nodejs-app .
          docker push integrationninjas/nodejs-app:latest
