name: Demo Action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build & Push Image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker image build -t ${{ secrets.DOCKERHUB_REPO }}/demo-nodejs-app .
          docker push ${{ secrets.DOCKERHUB_REPO }}/demo-nodejs-app:latest
