name: Demo Action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build & Push Image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "sjalal0228" --password-stdin
          docker image build -t sjalal0228/demo-nodejs-app .
          docker push sjalal0228/demo-nodejs-app:latest
